### PR TITLE
try cgns

### PR DESCRIPTION
**Pull request by jschueller**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tinyendian** [comment]
Hi @jschueller, thanks for taking this on - it seems that the HDF5-enabled cgns Windows builds have not made it to the conda-forge repository. The failed ParaView Windows cloud builds are using `cgns 4.2.0-h668289b_3`, which has `CG_BUILD_HDF5=0`, so compilation breaks with the same error that I found when I built ParaView on my Windows laptop using `conda build`,
```
%SRC_DIR%\VTK\ThirdParty\ioss\vtkioss\cgns\Iocgns_Utils.C(2922): fatal error C1189: #error:  "Not defined..."
```

**Comment by tinyendian** [comment]
OK, just realised that https://github.com/conda-forge/cgns-feedstock/pull/20 has not yet been merged.

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by tinyendian** [comment]
Hi @jschueller, the linker errors in the `ParaView` Windows builds can be fully resolved by rebuilding the `cgns` library with `-DH5_BUILT_AS_DYNAMIC_LIB`. The `CMakeLists.txt` in the `cgns` build system doesn't set this macro for the particular configuration of the Windows cloud build nodes (see code starting at line 234 in https://github.com/CGNS/CGNS/blob/v4.2.0/CMakeLists.txt), and downstream applications trying to link with the `cgns` DLL end up with missing symbols. Adding `add_definitions(-DH5_BUILT_AS_DYNAMIC_LIB)` around line 250, similar to the other cases, should hopefully fix this (I built everything successfully with a global `-DCMAKE_C_FLAGS="-DH5_BUILT_AS_DYNAMIC_LIB"` for `cgns`, but global flags are probably not a great solution).

Note that the `ParaView` build system needs to be fixed as well; I had to declare the HDF5 dependency explicitly in file `VTKExtensions/CGNSWriter/CMakeLists.txt` using something like
```
vtk_module_link(ParaView::VTKExtensionsCGNSWriter
  PRIVATE
    VTK::hdf5)
```
to avoid another missing symbols error.

**Pull request closed without merging**
